### ISSUE TITLE
Python 3.8?

### ISSUE THREAD

**Issue by magicmatt007** [newAM/idasen#128]
Hi, 

I tried to install this package on a Raspbian PI system which only has Python 3.7 and get this error:
"Could not find a version that satisfies the requirement idasen (from versions: ) No matching distribution found for idasen"

Does this package only work for Python 3.8? If so, could it be made available for Python 3.7 as well?

Thx
Matthias

**Comment by newAM** [comment]
It should be possible, just a minor pain because importlib metadata does not exist in 3.7.  Python 3.7 is the oldest python version still supported by the python foundation, would it be possible to use a newer python version?  This works on 3.8, 3.9, and 3.10.

As a quick hack you can copy the source locally (only two files), install `voluptuous` and `bleak` python packages, and delete all lines that reference `importlib`.

**Comment by magicmatt007** [comment]
My Raspbian OS "Buster" comes only with Python 3.7. My attempts to upgrade it to 3.8 or 3.9 failed...
But a couple of days ago Raspbian OS "Bullseye" got released and it comes with 3.9. So I took the opportunity and did a clean re-install with Bullseye.

-> I could now install idasen :-)

**Comment by newAM** [comment]
Excellent, glad to hear there was a newer version available for the pi!  I'll close the issue, if this didn't resolve it feel free to reopen.
